### ISSUE TITLE
winget install msys2

### ISSUE THREAD

**Issue by ctaggart** [msys2/msys2-installer#19]
I was hoping to be able to do a `winget install msys2`, but `winget search mysys2` came up empty.  

https://docs.microsoft.com/en-us/windows/package-manager/
https://docs.microsoft.com/en-us/windows/package-manager/package/repository
https://github.com/microsoft/winget-pkgs

**Comment by Biswa96** [comment]
First, the name is **MSYS2**. Second, why do you need Microsoft's winget to install msys2? MSYS2 already provides an installer, here https://github.com/msys2/msys2-installer/releases

**Comment by ctaggart** [comment]
That installer would be used. The package definition is just a way to link to it. It makes it convenient to find and install. Here is what the package definition could look like. When there is a silent switch #12 #3 for the installer, it can be added with a `Silent: /s`.

``` yaml
Id: MSYS2.MSYS2
Publisher: MSYS2
Name: MSYS2
Version: 20201109.0.0.0
License: GNU General Public License
InstallerType: EXE
LicenseUrl: https://github.com/msys2/msys2-runtime/blob/master/COPYING
AppMoniker: 
Description: Software Distribution and Building Platform for Windows
Homepage: https://www.msys2.org/
Installers:
  - Arch: x64
    InstallerType: EXE
    Url: https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20201109.exe
    Sha256: 274a11559ede8b892da63dacab30dcf968b811fe21caccc9a1fb9137a5e56062
# Generated by https://github.com/ptorr-msft/WinGetYamlGenerator
```
